project_id = "dtljebqpfogwhddxlbeb"

[functions.mercadopago-create-pix]
verify_jwt = false

[functions.mercadopago-check-payment]
verify_jwt = false

[functions.send-profit-summary]
verify_jwt = false

[functions.operator-inactive-check]
verify_jwt = false
